# .github/workflows/production-deploy.yml
name: Production Deployment

on:
  workflow_run:
    workflows: ["Staging Deployment"]
    types:
      - completed

jobs:
  ssh-command:
    runs-on: ubuntu-latest
    needs: manual-approval
    if: success() || failure()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EC2 VM and Deploy
        run: |
          echo "hello broooo!!!!"
          EOF
    environment:
      name: production
