name: CI/CD Pipeline

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Building the project..."
          # Add your build commands here

  approval:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/')
    
    steps:
      - name: Await Manual Approval
        run: echo "Awaiting manual approval from environment reviewers..."

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    if: needs.approval.result == 'success' && startsWith(github.ref, 'refs/heads/release/')

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here
