name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from a release branch
        id: check_branch
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^release/ ]]; then
            echo "Not a release branch. Exiting."
            exit 1
          fi

  pipeline:
    needs: approval
    runs-on: ubuntu-latest
    environment:
      name: production  # Replace with your environment name
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your testing commands here

      - name: Deploy
        run: |
          echo "Deploying..."
          # Add your deployment commands here
